version: "3.8"

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dbFoyer
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql

  app-timesheet:
    image: azello/tp-foyer-5.0.0
    depends_on:
      - mysqldb
    restart: on-failure
    ports:
      - "8089:8089"
    environment:
      spring.datasource.url: jdbc:mysql://mysqldb:3306/dbFoyer?createDatabaseIfNotExist=true
      spring.datasource.username: root
      spring.datasource.password: root
      spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQLDialect
      spring.jpa.hibernate.ddl-auto: update
    stdin_open: true
    tty: true
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    depends_on:
      - mysqldb
    ports:
      - "8082:80"
    environment:
      PMA_HOST: mysqldb
      PMA_USER: root
      PMA_PASSWORD: root
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin  # set admin password
    volumes:
      - grafana-storage:/var/lib/grafana
    restart: unless-stopped    
volumes:
  db:
  grafana-storage:
